#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and hi for 9th time

i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [[ "$i" == '9' ]]
    then
        echo "Hi"
    fi
    ((i++))
done
