#!/usr/bin/env bash
# This script is displaying numbers from 1-20 and some supersticious numbers

c=1
while [ $c -le 20 ]
do
    case $c in
        "4")
            echo "$c"
            echo "bad luck from China"
            ;;
        "9")
            echo "$c"
            echo "bad luck from Japan"
            ;;
        "17")
            echo "$c"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$c"
            ;;
    esac
    ((c++))
done
