#!/usr/bin/env bash
# This is the script that displays the content of the current directory in a list format
# Where only the part of the name after the first dash is to be displayed

for _ in *
do
    echo "$_" | cut -f 2 -d '-'
done
