#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely
# In between each iteration of the loop, must be added a sleep 2

while true
do
  echo "To infinity and beyond"
  sleep 2
done
