#!/usr/bin/env bash
# Bash script that display Infinity loop and sending signal
# and trap receive signal
trap "echo I am invincible!!!" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
